version: "3.8"

services:
  web:
    image: joelsanchz/prs3-front:latest
    container_name: mi_pagina_web
    ports:
      - "80:80"
    restart: always
  api:
    image: joelsanchz/prs3-back:latest
    container_name: mi_api
    ports:
      - "3000:3000"
    restart: always
