name: Deploy Terraform + Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Export Terraform variables from secrets
        run: |
          export TF_VAR_tenancy_ocid=${{secrets.TF_TENANCY_OCID}}
          export TF_VAR_user_ocid=${{secrets.TF_USER_OCID}}
          export TF_VAR_fingerprint=${{secrets.TF_FINGERPRINT}}
          export TF_VAR_private_key="${{secrets.TF_PRIVATE_KEY}}"
          export TF_VAR_region=${{secrets.TF_REGION}}
          export TF_VAR_compartment_ocid=${{secrets.TF_COMPARTMENT_OCID}}
          export TF_VAR_subnet_id=${{secrets.TF_SUBNET_ID}}
          export TF_VAR_availability_domain=${{secrets.TF_AVAILABILITY_DOMAIN}}
          export TF_VAR_ubuntu_image=${{secrets.TF_UBUNTU_IMAGE}}
          export TF_VAR_ssh_public_key="${{secrets.TF_SSH_PUBLIC_KEY}}"

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Obtener IP pública de la VM
        id: vm_ip
        run: echo "public_ip=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.TF_PRIVATE_KEY}}

      - name: Copiar y ejecutar setup_vm.sh
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.public_ip }}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: setup_vm.sh
          target: /tmp/

      - name: Ejecutar setup_vm.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.public_ip }}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            chmod +x /tmp/setup_vm.sh
            /tmp/setup_vm.sh ${{secrets.SSH_USER}}
            rm /tmp/setup_vm.sh

      - name: Copiar docker-compose.yml
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ env.public_ip }}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: docker-compose.yml
          target: "/home/${{secrets.SSH_USER}}/deploy/"

      - name: Ejecutar Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.public_ip }}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd /home/${{secrets.SSH_USER}}/deploy
            echo ${{secrets.DOCKER_TOKEN}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
            docker-compose down
            docker-compose pull
            docker-compose up -d --force-recreate
            docker logout
